/masacoord:
    ros__parameters:
        input_length: 0.512
        init_doa: 15.0
        eta: 0.3 #0.3 for sdr, stoi and scoreq
        smooth_weight: 0.65 #0.9 for sdr, 0.65 for stoi, 0.9 for scoreq
        quality_type: 'stoi' # can be: 'sdr', 'stoi, 'pesq', 'scoreq', or 'audbox'
        wait_for_qual: 1.5
        vad_threshold: 0.85
        max_time: 120.0
        merge_doas: True
        masa_order: [
          'beamformer',
          'demucs',
          'jack_write',
          'soundloc',
          'doaoptimizer_dummy',
          'freqselect',
          'theta_plot',
          'doa_plot',
        ]

